name: Build and Push Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "YOUR_DOCKER_USERNAME" --password-stdin

      - name: Build Image
        run: docker build -t YOUR_DOCKER_USERNAME/fastapi-app:v1 .

      - name: Push Image
        run: docker push YOUR_DOCKER_USERNAME/fastapi-app:v1